name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: SSH into Azure VM and deploy
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USER }}
        password: ${{ secrets.AZURE_VM_PASSWORD }}
        port: 22
        script: |
          # Clone the repo if not already present
          if [ ! -d "face_recognition" ]; then
            git clone https://github.com/yassineamri722/face_recognition.git
          fi
          cd face_recognition

          # Pull latest image
          docker pull yassineamri/face_recognition:latest

          # Stop and remove existing container if it exists
          docker stop face_recognition || true
          docker rm face_recognition || true

          # Run container
          docker run -d -p 5000:5000 --name face_recognition yassineamri/face_recognition:latest
