name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: SSH into Azure VM and deploy
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.AZURE_VM_HOST }}  # Use secret for Azure VM IP
        username: ${{ secrets.AZURE_VM_USER }}  # Use secret for the VM username
        password: ${{ secrets.AZURE_VM_PASSWORD }}  # Use secret for the VM password
        port: 22
        script: |
          # Check if the project directory exists, if not, clone the repository
          if [ ! -d "face_recognition" ]; then
            git clone https://github.com/yassineamri722/face_recognition.git
          fi
          cd face_recognition
          
          # Pull the latest version of the Docker image from DockerHub
          docker pull yassineamri/face_recognition:latest
          
          # Stop any existing container running on port 5000 (if any)
          docker ps -q -f "name=face_recognition" | grep -q . && docker stop face_recognition
          
          # Run the container on port 5000
          docker run -d -p 5000:5000 --name face_recognition yassineamri/face_recognition:latest
